

title: Daniel
email: danielirano@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Esse é um projeto desenvolvido na aula de encontrabilidade, ministrada pelo Prof Felipe.
  Ao lado você pode me encontrar em todas as plataformas digitais. Acompanhe já!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: danielirano
github_username:  danielirano
instagram_username: danielirano
linkedin_username: danielirano


# Build settings
theme: minima
plugins:
  - jekyll-feed

